apiVersion: v1
kind: Config
clusters:
- cluster:
    #certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTlRreE9UWTBPRFV3SGhjTk1qVXdPVE13TURFME1USTFXaGNOTXpVd09USTRNREUwTVRJMQpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTlRreE9UWTBPRFV3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRcE5GZjg5T3ZpV1hCZ1JublZ6K3JMUCs2czA1VTlhZTV1T0FpTDh4dVUKVkJDc0FQdUxkMExacHJiUndoR3JrejhTYXQzZzB1SXd1Z1N4WGt5MEZ3ajhvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVpoM1J4MGVTTXZZbVhSRjJsbDFqCnQ4RUREWEF3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQU95dnhXU1pVQVowSnB4UXlNcFZBUmNxNXVJYkVVM2sKa2E4QTVuOVpTMDZtQWlFQTFwZE9xenZvcE1LN24zNkQ1d0NZa25vRjAvSURUUWVCWW9tQUpZcVBQb1U9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    insecure-skip-tls-verify: true  
    server: https://54.91.9.122:6443
  name: cteam3
contexts:
- context:
    cluster: cteam3
    namespace: team3
    user: team3
  name: team3-context
current-context: team3-context
users:
- name: team3
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjBQNTJqUzRnZWg0VlJqSmUxLUJ3QW0tV3ltbS1DcFdtRThMd3hVTWZtT28ifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiLCJrM3MiXSwiZXhwIjoxNzY0MTMxNjE2LCJpYXQiOjE3NjQxMTcyMTYsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiNzAxNzZlNWYtNGNlNS00N2NkLTgyMTUtOTBlNGIyMWExMzIzIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJ0ZWFtMyIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJ0ZWFtMyIsInVpZCI6ImI2M2VhZGE0LWRmMjQtNGFlNS04OGRlLWJjZjgzYjgzZDgwOSJ9fSwibmJmIjoxNzY0MTE3MjE2LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6dGVhbTM6dGVhbTMifQ.nhbqTPfHZaEBb0lk7oM2penalpKHvKAik8ci6m16dSFUgFmVd11KwDjfWZG7PgTTW0l_ug6_iTfNFQpOMCBVcZmyYDmWLB_RDycPBcWNplgzu91uvSHQEkgx2gZOg2woK8kANtNNfTBuOsOVOEWHnyzW0BZm2wljAcgp-LZBs_JHnEJNpyKnToYOpGOIvJzApnE1Sqh1n8ELc-heDcf02WxFd1ZaEIo8GxwDkamqwXRFSGPLjsI0Ls0-tuPB_mRt2eZk5cPAFcSEB_7bUYxkwXwDUltjVP5zEpS1Z4bWwdbIXGYKBafv0AdqXOmMq0WbgjG-icKEr1rdrDK-1yBnew
